name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # замените это на вашу основную ветку

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_BACKEND_REGISTRY }}
        region: eu-central-1
      
    - name: Build Docker image
      run: docker build -t backend .
      
    - name: Tag Docker image
      run: docker tag my-docker-image ${{ secrets.AWS_BACKEND_REGISTRY }}:latest
      
    - name: Push Docker image to Amazon ECR
      run: docker push ${{ secrets.AWS_BACKEND_REGISTRY }}:latest